# Generated by Django 4.2.16 on 2024-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='usableQuantity',
            new_name='currentStock',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='safeStockQuantity',
            new_name='safeStock',
        ),
        migrations.RemoveField(
            model_name='component',
            name='image',
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='costPerUnit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='maximumStock',
            field=models.PositiveIntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='unitMeasure',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
