# Generated by Django 4.2.16 on 2024-11-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0002_rename_usablequantity_component_currentstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityUsed', models.PositiveIntegerField()),
                ('dateAndTime', models.DateTimeField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='Components.component')),
            ],
        ),
    ]
