# Generated by Django 4.2.16 on 2025-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0003_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='currentStock',
            field=models.IntegerField(),
        ),
    ]
